name: AevorinAuth
version: "${version}"
main: dev.aevorinstudios.aevorinAuth.AevorinAuth
api-version: "1.21"
folia-supported: true
softdepend: [ProtocolLib]
commands:
  auth:
    description: Main command for AevorinAuth.
    usage: /auth reload
    permission: aevorinauth.admin
  register:
    description: Register an account.
    usage: /register <password> <confirmPassword>
  login:
    description: Login to your account.
    usage: /login <password>
  unregister:
    description: Unregister your account.
    usage: /unregister <password>
  changepassword:
    description: Change your account password.
    usage: /changepassword <oldPassword> <newPassword>
    aliases: [cpw]
